### ISSUE TITLE
Marker mode doesnt seem to work? 

### ISSUE THREAD

**Issue by CodificationCodes** [Darthan184/Thrust-Assist-SFS1#1]
Ive been trying to catch the starship with the latest version of the Thrust Assist mod for SFS, but it just doesnt seem to work? Its important to note ive tried it on other ships too and it didnt work. I will link a video below to show. (Sorry for poor quality, i had to compress because of Github)

https://github.com/user-attachments/assets/3497f183-3c76-4728-90bc-90d87c244c4a

**Comment by Darthan184** [comment]
Marker assist is for controlling horizontal velocity and is best used from orbit for determing when to deorbit. Surface assist is for controlling vertical velocity and is best used for landing or hovering. In the case you are using it in, you want to use 'surface' assist and not 'marker' assist. It is possible to have both 'marker' and 'surface' assist on at the same time but marker assist is not very useful when moving almost vertically or near the surface so it is better to use surface assist alone in that case. Also there is a bug that causes the engines to cut off when you are both moving away and pointing away from the mark when 'marker' assist is on - even if 'surface' assist is on at the same time.

The may be another issue with this use case. I'm not quite sure how high you need to hover in order to catch the starship but the height control may not be fine enough - it currently only allows powers of 2. I've made a note to add a finer height control.

**Comment by Darthan184** [comment]
I've fixed the engine cutoff bug then used to occure while hovering with marker assis left on and add a fine (+-0.5 m) height control
